In [18]:
import requests
import websocket
import datetime
import json
import numpy as np
import pandas as pd

In [24]:
api_key = 'bu6l53n48v6pfj0oklv0'
end = datetime.datetime(2020,10,1,0,0).strftime('%s')
start = datetime.datetime(2020,7,1,0,0).strftime('%s')
facebook = 'FB'
apple = 'AAPL'
amazon = 'AMZN'
netflix = 'NFLX'
google = 'GOOG'
companies = ['FB', 'AAPL', 'AMZN', 'NFLX', 'GOOG']

In [25]:
stock_quotes = pd.DataFrame()
for c in companies:
    r = requests.get('https://finnhub.io/api/v1/stock/candle?symbol=' + c + '&resolution=D&from=' + start+ '&to=' + end + '&token=bu6l53n48v6pfj0oklv0')
    y = json.loads(json.dumps(r.json()))
    t = [""]*len(y["t"])
    for x in range (0,len(t)):
        t[x] = datetime.datetime.fromtimestamp(y["t"][x]).strftime('%y-%m-%d')
    company_quote = pd.DataFrame({
    'Company' : [c]*len(y["v"]),
    'Open' : np.round(y["o"]),
    'Close' : np.round(y["c"]),
    'Volume' : y["v"],
    'Date' : t
    })
    stock_quotes = pd.concat([stock_quotes, company_quote], axis = 0).reset_index(drop=True)

In [26]:
stock_quotes

    Company    Open   Close    Volume      Date
0        FB   228.0   238.0  43399740  20-07-01
1        FB   239.0   233.0  30633620  20-07-02
2        FB   234.0   240.0  26206158  20-07-06
3        FB   239.0   241.0  27887786  20-07-07
4        FB   238.0   244.0  29791340  20-07-08
5        FB   245.0   244.0  22174896  20-07-09
6        FB   244.0   245.0  22982716  20-07-10
7        FB   247.0   239.0  24674874  20-07-13
8        FB   237.0   240.0  23378056  20-07-14
9        FB   242.0   240.0  19133562  20-07-15
10       FB   238.0   241.0  18880704  20-07-16
11       FB   241.0   242.0  18152412  20-07-17
12       FB   240.0   245.0  20872224  20-07-20
13       FB   246.0   242.0  19409688  20-07-21
14       FB   240.0   240.0  15427885  20-07-22
15       FB   240.0   233.0  21771802  20-07-23
16       FB   230.0   231.0  18325812  20-07-24
17       FB   231.0   234.0  13163083  20-07-27
18       FB   235.0   230.0  14170112  20-07-28
19       FB   231.0   233.0  13588317  20-07-29
20       FB   230.0   234.0  20615306  20-07-30
21       FB   256.0   254.0  53030036  20-07-31
22       FB   253.0   252.0  23134104  20-08-03
23       FB   252.0   250.0  17183532  20-08-04
24       FB   250.0   249.0  13088361  20-08-05
25       FB   249.0   265.0  45241612  20-08-06
26       FB   264.0   268.0  72766368  20-08-07
27       FB   268.0   263.0  30248826  20-08-10
28       FB   260.0   256.0  28238284  20-08-11
29       FB   259.0   260.0  21428328  20-08-12
..      ...     ...     ...       ...       ...
290    GOOG  1553.0  1548.0   1660600  20-08-19
291    GOOG  1543.0  1582.0   1706900  20-08-20
292    GOOG  1577.0  1580.0   1446500  20-08-21
293    GOOG  1594.0  1588.0   2819800  20-08-24
294    GOOG  1582.0  1608.0   2247100  20-08-25
295    GOOG  1608.0  1652.0   3993400  20-08-26
296    GOOG  1654.0  1634.0   1861600  20-08-27
297    GOOG  1633.0  1644.0   1499800  20-08-28
298    GOOG  1648.0  1634.0   3646806  20-08-31
299    GOOG  1637.0  1661.0   1826700  20-09-01
300    GOOG  1674.0  1728.0   2511200  20-09-02
301    GOOG  1710.0  1642.0   3107800  20-09-03
302    GOOG  1624.0  1591.0   2608600  20-09-04
303    GOOG  1534.0  1532.0   5218900  20-09-08
304    GOOG  1558.0  1557.0   1774700  20-09-09
305    GOOG  1561.0  1532.0   1618600  20-09-10
306    GOOG  1536.0  1521.0   1597100  20-09-11
307    GOOG  1539.0  1519.0   1694300  20-09-14
308    GOOG  1536.0  1541.0   1331100  20-09-15
309    GOOG  1556.0  1521.0   1311700  20-09-16
310    GOOG  1496.0  1496.0   1879800  20-09-17
311    GOOG  1498.0  1460.0   3103900  20-09-18
312    GOOG  1440.0  1431.0   2888800  20-09-21
313    GOOG  1450.0  1465.0   1583200  20-09-22
314    GOOG  1459.0  1415.0   1657400  20-09-23
315    GOOG  1411.0  1428.0   1450200  20-09-24
316    GOOG  1433.0  1445.0   1323000  20-09-25
317    GOOG  1474.0  1465.0   2007900  20-09-28
318    GOOG  1470.0  1469.0    978200  20-09-29
319    GOOG  1467.0  1470.0   1700600  20-09-30

[320 rows x 5 columns]

In [27]:
stock_quotes.to_csv('stock_quotes.csv')